require: rubocop-rails

AllCops:
  Exclude:
    - "db/schema.rb"
    - "config/**/*"
    - "bin/**/*"
    - "data/**/*"
    - "lib/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "db/**/*"
    - "node_modules/**/*"
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/LineLength:
  Enabled: false

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Rails/HelperInstanceVariable:
  Enabled: false

# disable for now
# Lint/NestedMethodDefinition:
#   Enabled: false
# Style/ClassVars:
#   Enabled: false
# Style/RescueModifier:
#   Enabled: false
# Style/AccessorMethodName:
#   Enabled: false
# Style/PredicateName:
#   Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
