version: '3.7'

services:
    database:
        image: mariadb
        environment:
            - MYSQL_DATABASE=dodona
            - MYSQL_ROOT_PASSWORD=dodona
        ports:
            - "3306:3306"

    dodona:
        hostname: dodona.localhost
        build: .
        depends_on:
            - database
        ports:
            - "3000:3000"