name: Deploy

on:
  pull_request:
    types:
      - labeled

jobs:
  mestra:
    if: ${{ github.event.action == 'review_requested' || (github.event.action == 'labeled' && github.event.label.name == 'deploy') }}
    environment: 
      name: mestra
      url: https://mestra.ugent.be
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous deployments
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESTRA_KEY }}
        known_hosts: ${{ secrets.MESTRA_HOST }}
    - name: Run deploy
      run: |
        echo "$GITHUB_SHA" | ssh -p 4840 dodona@mestra.ugent.be
    - name: Remove deploy label
      uses: buildsville/add-remove-label@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        label: deploy
        type: remove
