name: Lint

on: [push]

jobs:
  ruby:
    name: Ruby
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use ruby from .ruby-version
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Lint with rubocop
      env:
        RAILS_ENV: "test"
      run: |
        bundle exec rubocop -c  .rubocop.yml

  javascript:
    name: JavaScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Get the Yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn dependencies
      uses: actions/cache@v2.1.4
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: |
        yarn install
    - name: Lint
      run: |
        yarn lint --quiet
