name: Publish Docker image

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to the container registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Download the latest image for caching
      run: docker pull ghcr.io/dodona-edu/dodona:develop-latest
    - name: Build the new image
      run: docker build . -t ghcr.io/dodona-edu/dodona:develop-latest --cache-from ghcr.io/dodona-edu/dodona:develop-latest
    - name: Push the new image
      run: docker push ghcr.io/dodona-edu/dodona:develop-latest