# Will restart delayed job on all worker servers
name: Restart workers

on:
  workflow_dispatch:

concurrency: 
  group: restart-workers
  cancel-in-progress: true

jobs:
  deploy:
    environment: 
      name: workers
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESTRA_KEY }}
        known_hosts: ${{ secrets.MESTRA_HOST }}
    - name: Run deploy
      run: |
        echo "restart workers" | ssh -p 4840 dodona@mestra.ugent.be
