# Will restart delayed job on all worker servers

name: Deploy workers

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: 
      name: workers
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous deployments
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.MESTRA_KEY }}
        known_hosts: ${{ secrets.MESTRA_HOST }}
    - name: Run deploy
      run: |
        echo "deploy workers" | ssh -p 4840 dodona@mestra.ugent.be
