name: Ruby

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: "test"
      TEST_DATABASE_URL: "mysql2://root:dodona@127.0.0.1:3306/dodona_test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "dodona_test"
          MYSQL_ROOT_PASSWORD: "dodona"
          MYSQL_HOST: "localhost"
        ports:
        - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use ruby 2.7
      uses: ruby/setup-ruby@v1.47.0
      with:
        ruby-version: 2.7.2
    - name: Use node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache Ruby dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Get the Yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        yarn install
    - name: Run tests
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        git config --global user.email "dodona@ugent.be"
        git config --global user.name "Dodona"
        sudo sysctl fs.inotify.max_user_watches=524288
        sudo sysctl -p
        bundle exec rails test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use ruby 2.7
      uses: ruby/setup-ruby@v1.47.0
      with:
        ruby-version: 2.7.2
    - name: Cache Ruby dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install dependencies
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Lint with rubocop
      env:
        RAILS_ENV: "test"
      run: |
        bundle exec rubocop -c  .rubocop.yml
