name: System tests

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: "test"
      TEST_DATABASE_URL: "mysql2://root:dodona@127.0.0.1:3306/dodona_test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "dodona_test"
          MYSQL_ROOT_PASSWORD: "dodona"
          MYSQL_HOST: "localhost"
        ports:
        - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use ruby 2.7
      uses: ruby/setup-ruby@v1.47.0
      with:
        ruby-version: 2.7.2
        bundler-cache: true
    - name: Use node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup chromium-chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Get the Yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install JS dependencies
      run: |
        yarn install
    - name: Show installed chrome version
      run: |
        google-chrome --version
    - name: Run tests
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        PARALLEL_WORKERS: 1
      run: |
        git config --global user.email "dodona@ugent.be"
        git config --global user.name "Dodona"
        bundle exec rails test:system
    - name: Upload screenshot artifacts
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: screenshots-failure
        path: tmp/screenshots
