name: System tests

on: [push]

jobs:
  test:
    env:
      RAILS_ENV: "test"
      TEST_DATABASE_URL: "mysql2://root:dodona@127.0.0.1:3306/dodona_test"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_DATABASE: "dodona_test"
          MYSQL_ROOT_PASSWORD: "dodona"
          MYSQL_HOST: "localhost"
        ports:
        - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Use ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Use node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Chrome
      run: |
        sudo apt update
        sudo apt install -y libgconf-2-4 wget xvfb --no-install-recommends
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable --no-install-recommends
    - name: Setup chromium-chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Cache Ruby dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Get the Yarn cache directory
      id: yarn-cache
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache Yarn dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: |
        gem install bundler:2.0.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        yarn install
    - name: Show installed chrome version
      run: |
        google-chrome --version
    - name: Run tests
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        git config --global user.email "dodona@ugent.be"
        git config --global user.name "Dodona"
        bundle exec rails test:system
    - name: Upload screenshot artifacts
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: screenshots-failure
        path: tmp/screenshots
